# Generated by Django 6.1.1 on 2026-09-04 14:34

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ADR-001: pg_trgm нужен для GIN-индексов name/article ниже.
        TrigramExtension(),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='запущен')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('kind', models.CharField(choices=[('reference', 'Справочники (номенклатура/виды/папки)'), ('stock', 'Остатки')], max_length=20, verbose_name='тип')),
                ('source_file', models.CharField(max_length=500, verbose_name='файл-источник')),
                ('file_hash', models.CharField(blank=True, help_text='защита от повторного импорта того же файла', max_length=64, verbose_name='хэш файла')),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('partial', 'Частично'), ('error', 'Ошибка')], default='ok', max_length=20, verbose_name='статус')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='строк всего')),
                ('rows_created', models.PositiveIntegerField(default=0, verbose_name='создано')),
                ('rows_updated', models.PositiveIntegerField(default=0, verbose_name='обновлено')),
                ('rows_failed', models.PositiveIntegerField(default=0, verbose_name='не легло')),
                ('error_text', models.TextField(blank=True, verbose_name='текст ошибки')),
            ],
            options={
                'verbose_name': 'лог импорта',
                'verbose_name_plural': 'логи импорта',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NomenclatureKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_1c', models.CharField(max_length=20, unique=True, verbose_name='код 1С')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'вид номенклатуры',
                'verbose_name_plural': 'виды номенклатуры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_1c', models.CharField(max_length=20, unique=True, verbose_name='код 1С')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('is_visible', models.BooleanField(default=True, help_text='ADR-005/ADR-009: исключить недоступные площадки (например, удалённые стройки) из витрины остатков', verbose_name='показывать конструкторам')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_1c', models.CharField(max_length=20, unique=True, verbose_name='код 1С')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.folder', verbose_name='родительская папка')),
            ],
            options={
                'verbose_name': 'папка номенклатуры',
                'verbose_name_plural': 'папки номенклатуры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_code', models.CharField(max_length=50, verbose_name='код позиции')),
                ('reason', models.TextField(verbose_name='причина')),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='catalog.importlog', verbose_name='импорт')),
            ],
            options={
                'verbose_name': 'ошибка строки импорта',
                'verbose_name_plural': 'ошибки строк импорта',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_1c', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='код 1С')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='артикул')),
                ('base_unit', models.CharField(blank=True, max_length=50, verbose_name='единица измерения')),
                ('is_active', models.BooleanField(default=True, help_text='False — помечена на удаление в 1С (ADR-009)', verbose_name='актуальна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено при импорте')),
                ('total_available', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='доступный остаток (сумма по видимым складам)')),
                ('is_stale', models.BooleanField(default=False, help_text='total_available >= порогу по ThresholdRule (ADR-004)', verbose_name='залежалось')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.folder', verbose_name='папка')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.nomenclaturekind', verbose_name='вид номенклатуры')),
            ],
            options={
                'verbose_name': 'номенклатура',
                'verbose_name_plural': 'номенклатура',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('description', models.TextField(verbose_name='описание: что нужно и зачем')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='единица измерения')),
                ('gost_or_article', models.CharField(blank=True, max_length=255, verbose_name='ГОСТ / артикул')),
                ('analog_url', models.URLField(blank=True, verbose_name='ссылка на аналог у поставщика')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('entered', 'Заведена в 1С'), ('closed', 'Закрыта'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='статус')),
                ('resolution_comment', models.TextField(blank=True, verbose_name='комментарий к решению')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='решение принято')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('guessed_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.nomenclaturekind', verbose_name='предполагаемый вид')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто принял решение')),
                ('reviewed_not_matching', models.ManyToManyField(blank=True, related_name='+', to='catalog.nomenclature', verbose_name='просмотрено и не подошло')),
                ('similar_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.nomenclature', verbose_name='похожая позиция (нашлась)')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='порог (в базовой ЕИ)')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold_rules', to='catalog.folder', verbose_name='папка')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold_rules', to='catalog.nomenclaturekind', verbose_name='вид номенклатуры')),
                ('nomenclature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold_rules', to='catalog.nomenclature', verbose_name='номенклатура')),
            ],
            options={
                'verbose_name': 'правило порога остатков',
                'verbose_name_plural': 'правила порога остатков',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='остаток')),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='в резерве')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено при импорте')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='catalog.nomenclature', verbose_name='номенклатура')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='catalog.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'остаток на складе',
                'verbose_name_plural': 'остатки на складах',
            },
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='nomenclature_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=django.contrib.postgres.indexes.GinIndex(fields=['article'], name='nomenclature_article_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['is_active'], name='catalog_nom_is_acti_45a05f_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['is_stale'], name='catalog_nom_is_stal_b6bde0_idx'),
        ),
        migrations.AddConstraint(
            model_name='thresholdrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__isnull', False), ('folder__isnull', True), ('nomenclature__isnull', True)), models.Q(('kind__isnull', True), ('folder__isnull', False), ('nomenclature__isnull', True)), models.Q(('kind__isnull', True), ('folder__isnull', True), ('nomenclature__isnull', False)), _connector='OR'), name='threshold_rule_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('nomenclature', 'warehouse'), name='unique_stock_balance_per_warehouse'),
        ),
    ]
